name: gobblet-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py38hef030d1_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - blinker=1.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38hef030d1_1005
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2023.01.10=hecd8cb5_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=py38hecd8cb5_0
  - cffi=1.15.1=py38hb368cf1_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.0=py38ha6c3189_0
  - frozenlist=1.3.3=py38hef030d1_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.42.0=py38ha29bfda_0
  - gym-notices=0.0.8=pyhd8ed1ab_0
  - h5py=2.10.0=nompi_py38h106b333_102
  - hdf5=1.10.5=nompi_h500d6d3_1114
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - libblas=3.9.0=16_osx64_openblas
  - libcblas=3.9.0=16_osx64_openblas
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.2=hecd8cb5_6
  - libgfortran=5.0.0=11_3_0_h97931a8_27
  - libgfortran5=11.3.0=h082f757_27
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm11=11.1.0=hd011deb_2
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libprotobuf=3.20.1=h8346a28_0
  - llvm-openmp=15.0.7=h61d9ccf_0
  - llvmlite=0.39.1=py38h8346a28_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.2=py38hef030d1_0
  - mkl=2022.2.1=h44ed08c_16952
  - multidict=6.0.4=py38hef030d1_0
  - ncurses=6.4=hcec6c5f_0
  - ninja=1.11.0=h1b54a9f_0
  - numba=0.56.4=py38hab356c4_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1s=hca72f7f_0
  - packaging=23.0=pyhd8ed1ab_0
  - pip=22.3.1=py38hecd8cb5_0
  - pluggy=1.0.0=py38hecd8cb5_1
  - py=1.11.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.1.2=py38hecd8cb5_0
  - python=3.8.16=h218abb5_2
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=cpu_py38h03065b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - readline=8.2=hca72f7f_0
  - requests=2.28.2=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h6db0672_2
  - sqlite=3.40.1=h880c91c_0
  - tbb=2021.7.0=hb8565cd_1
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py38ha6c3189_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tianshou=0.4.11=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - tomli=2.0.1=py38hecd8cb5_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h6c40b1e_1
  - yarl=1.8.2=py38hef030d1_0
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - aiohttp-cors==0.7.0
      - astunparse==1.6.3
      - bleach==6.0.0
      - blessed==1.19.1
      - build==0.10.0
      - colorful==0.5.5
      - contourpy==1.0.7
      - cycler==0.11.0
      - decorator==5.1.1
      - distlib==0.3.6
      - dm-tree==0.1.8
      - docopt==0.6.2
      - docutils==0.19
      - filelock==3.9.0
      - flatbuffers==23.1.21
      - fonttools==4.38.0
      - gast==0.4.0
      - google-api-core==2.11.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.58.0
      - gpustat==1.0.0
      - gym==0.23.1
      - gymnasium==0.27.1
      - gymnasium-notices==0.0.1
      - hanabi-learning-environment==0.0.4
      - imageio==2.25.0
      - importlib-resources==5.10.2
      - jaraco-classes==3.2.3
      - jax-jumpy==0.2.0
      - jedi==0.10.0
      - jsonschema==4.17.3
      - keras==2.11.0
      - keyring==23.13.1
      - kiwisolver==1.4.4
      - libclang==15.0.6.1
      - lz4==4.3.2
      - markdown-it-py==2.1.0
      - matplotlib==3.6.3
      - mdurl==0.1.2
      - more-itertools==9.0.0
      - msgpack==1.0.4
      - networkx==3.0
      - numpy==1.22.0
      - nvidia-ml-py==11.495.46
      - opencensus==0.11.1
      - opencensus-context==0.1.3
      - opencv-python==4.7.0.68
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - pettingzoo==1.22.3
      - pillow==9.4.0
      - pipreqs==0.4.11
      - pkginfo==1.9.6
      - pkgutil-resolve-name==1.3.10
      - platformdirs==2.6.2
      - prometheus-client==0.16.0
      - protobuf==3.19.6
      - psutil==5.9.4
      - py-spy==0.3.14
      - pydantic==1.10.4
      - pygame==2.1.2
      - pygments==2.14.0
      - pymunk==6.4.0
      - pyparsing==3.0.9
      - pyproject-hooks==1.0.0
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - ray==2.2.0
      - readme-renderer==37.3
      - requests-toolbelt==0.10.1
      - rfc3986==2.0.0
      - rich==13.3.0
      - rlcard==1.0.5
      - scikit-image==0.19.3
      - scipy==1.10.0
      - setuptools==64.0.2
      - smart-open==6.3.0
      - supersuit==3.7.1
      - tabulate==0.9.0
      - tensorboardx==2.5.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - tensorflow-probability==0.19.0
      - termcolor==2.2.0
      - tifffile==2023.1.23.1
      - tinyscaler==1.2.4
      - twine==4.0.2
      - typer==0.7.0
      - virtualenv==20.17.1
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - wrapt==1.14.1
      - yarg==0.1.9
prefix: /Users/elliottower/anaconda3/envs/gobblet-rl
